version: "3.8"

services:
  server:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./server:/app/server
    ports:
      - "8000:80"
    environment:
      - VARIABLE_NAME=app
      - PORT=80
  